# Generated by Django 5.1.15 on 2026-07-19 07:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='riders.rider')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='fleet.vehicle')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payroll.expensecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.CharField(choices=[('fleet_enabled', 'Fleet Enabled'), ('base_amount', 'Base Amount'), ('base_min_hours', 'Base Min Hours'), ('base_min_rides', 'Base Min Rides'), ('commission_rate', 'Commission Rate'), ('revenue_cap', 'Revenue Cap'), ('growth_rate', 'Growth Rate'), ('ramp', 'Ramp'), ('streak_length', 'Streak Length'), ('streak_bonus', 'Streak Bonus'), ('monthly_floor', 'Monthly Floor'), ('yango_bonus_table', 'Yango Bonus Table')], max_length=32)),
                ('value', models.TextField()),
                ('effective_from', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parameter', 'effective_from'), name='uniq_payconfig_param_date')],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('times_target_missed', models.PositiveIntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_advances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_cash_variance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_processed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_model', models.CharField(choices=[('legacy', 'Legacy'), ('vpe', 'Vpe')], default='legacy', max_length=16)),
                ('flagged', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='riders.rider')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='riders.rider')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='payroll.salarypayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_qualifying_date', models.DateField(blank=True, null=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='riders.rider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('english_date', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('prize', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('growth', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('daily_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gates_applied', models.JSONField(blank=True, default=dict)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('computed', 'Computed'), ('locked', 'Locked')], default='computed', max_length=16)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_records', to='riders.rider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rider', 'english_date'), name='uniq_pay_record_rider_date')],
            },
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['rider', 'period_from', 'period_to'], name='payroll_sal_rider_i_e57e1c_idx'),
        ),
    ]
