# Generated by Django 5.1.15 on 2026-07-19 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(max_length=16, unique=True)),
                ('plate_number', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('battery_details', models.CharField(blank=True, max_length=255)),
                ('insurance_issue_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('tax_expiry', models.DateField(blank=True, null=True)),
                ('service_due_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('servicing_payment', models.CharField(blank=True, max_length=64)),
                ('odometer_reading', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('location_branch', models.CharField(blank=True, max_length=128)),
                ('gps_installed', models.CharField(blank=True, max_length=16)),
                ('gps_number', models.CharField(blank=True, max_length=64)),
                ('gps_id_password', models.CharField(blank=True, max_length=128)),
                ('scooter_branding', models.CharField(blank=True, max_length=128)),
                ('yango_branding_date', models.DateField(blank=True, null=True)),
                ('branding_payment', models.CharField(blank=True, max_length=64)),
                ('brandwrap_expire_date', models.DateField(blank=True, null=True)),
                ('bluebook_issue_date', models.DateField(blank=True, null=True)),
                ('bluebook_expiry_date', models.DateField(blank=True, null=True)),
                ('in_servicing_since', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('odometer_at_service', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_history', to='fleet.vehicle')),
            ],
            options={
                'verbose_name_plural': 'service histories',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('battery_service', 'Battery Service'), ('tire_replacement', 'Tire Replacement'), ('brake_service', 'Brake Service'), ('electrical_repair', 'Electrical Repair'), ('accident_repair', 'Accident Repair')], max_length=32)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('evening', 'Evening'), ('night', 'Night')], default='day', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=16)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='riders.rider')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('rider',), name='uniq_active_assignment_per_rider'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle',), name='uniq_active_assignment_per_vehicle')],
            },
        ),
    ]
