# Generated by Django 5.1.15 on 2026-07-19 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_submission_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('secondary_phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('marital_status', models.CharField(blank=True, max_length=16)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('permanent_address', models.CharField(blank=True, max_length=255)),
                ('temporary_address', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=64)),
                ('citizenship_number', models.CharField(blank=True, max_length=64)),
                ('citizenship_issue_date', models.CharField(blank=True, max_length=32)),
                ('citizenship_issue_district', models.CharField(blank=True, max_length=64)),
                ('citizenship_image_url', models.CharField(blank=True, max_length=512)),
                ('nid_number', models.CharField(blank=True, max_length=64)),
                ('nid_issue_date', models.CharField(blank=True, max_length=32)),
                ('nid_issue_district', models.CharField(blank=True, max_length=64)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_issue_date', models.CharField(blank=True, max_length=32)),
                ('license_issue_district', models.CharField(blank=True, max_length=64)),
                ('license_type', models.CharField(blank=True, max_length=32)),
                ('license_image_url', models.CharField(blank=True, max_length=512)),
                ('driving_experience', models.CharField(blank=True, max_length=64)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('father_phone', models.CharField(blank=True, max_length=32)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('mother_phone', models.CharField(blank=True, max_length=32)),
                ('spouse_name', models.CharField(blank=True, max_length=255)),
                ('spouse_phone', models.CharField(blank=True, max_length=32)),
                ('grandfather_name', models.CharField(blank=True, max_length=255)),
                ('grandmother_name', models.CharField(blank=True, max_length=255)),
                ('family_address', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=64)),
                ('relationship_proof_url', models.CharField(blank=True, max_length=512)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=16)),
                ('salary_structure', models.CharField(blank=True, max_length=64)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_ride_target', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_supervisor', models.CharField(blank=True, max_length=255)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bank_account_details', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('yango_driver_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('fleet_pilot', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='riders_ride_full_na_361874_idx')],
            },
        ),
    ]
