# Generated by Django 5.1.15 on 2026-07-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rider',
            constraint=models.UniqueConstraint(condition=models.Q(('yango_driver_id', ''), _negated=True), fields=('yango_driver_id',), name='uniq_rider_yango_driver_id'),
        ),
    ]
